# -*- coding: utf-8 -*-
"""matplotlib_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xgqj5h4YiEAQn4tIO1NGcTfI1bTaSGhl
"""

#matplotlib kütüphanesi daha çok  görselliştirme amaçlı kullanılır.

#install datasets library
#!pip install datasets

#import libraries
import pandas as pd
from datasets import load_dataset

#loading data
dataset=load_dataset('lukebarousse/data_jobs')
df=dataset['train'].to_pandas()

#data cleanup
df["job_posted_date"]=pd.to_datetime(df["job_posted_date"])

!pip install --upgrade huggingface_hub

!pip install --upgrade datasets

!pip list

!pip list matplotlib

import matplotlib

import matplotlib.pyplot  as plt
import numpy as np
#matplotlib.pyplot  modülü, Python programlama dilinde veri görselleştirme (grafik çizimi) yapmak için kullanılır.

x = np.arange(0, 5, 0.1) #o dan başlayıp 0.1 artarak bi numpy dizisi oluşturur ve bu grafiğin  x eksenidir
y = np.sin(x) #y eksenine karşılık gelen değerler
plt.plot(x, y) # bu değerlere uygun  çizgi grafikleri oluşturmak için
plt.show()#yapılan grafiği göstermek için

plt.scatter(x,y)
plt.show()

