# -*- coding: utf-8 -*-
"""pandas_project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SV1SaoFTgYVSb_RgH9SBhK749ogvPb7R

**PANDAS**
"""

df.salary_year_avg.notna()

