# -*- coding: utf-8 -*-
"""pandas_project2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WErqzTHt0c5Oz0j1wcmd7uuIkuPyNAcm
"""

import pandas as pd
from datasets import load_dataset

#loading data
dataset=load_dataset('lukebarousse/data_jobs')
df=dataset['train'].to_pandas()

pip install --upgrade huggingface_hub

!pip install --upgrade datasets

df.info()

df

df.job_posted_date[0]

dt=pd.to_datetime(df.job_posted_date)

type(dt)

dt

df["job_posted_date"]=pd.to_datetime(df.job_posted_date)

df.info()

df.job_posted_date.dt.month

df['job_posted_month']=df.job_posted_date.dt.month

df.info()

df.job_posted_month

df["job_posted_day"]=df.job_posted_date.dt.day

df.info()

df

df.job_posted_day

df.sort_values("job_posted_day",inplace=True) #inplace metodu otomotikmen false değerindedir bu metodu true olarak döndürürsek orijinal dataframe üzerinde işlem yapmamızı sağlar
#ve bu değer geri döndürülemez olduğu için orojinal datafram üzerinde daha sonra yapacağım değişiklikler üzerinde datafremimi yedeklemem lazım.

df

df.drop(labels="salary_hour_avg",axis=1) #drop metodu istediğim bi kısmı silmek için kullanılır axis 1 ise salary hour avg nin sütununu siler 0 ise satırını siler.
#kalıcı  yapmak istersem inplace metodunu kullanırım.

df.drop(labels="salary_year_avg",axis=1,inplace=True)

df

df.dropna(subset=["salary_hour_avg"]) #salary_hour_avg deki sütunlara bakar ve değerleri NaN olanları siler.

df.info()

df.dropna(subset=["salary_hour_avg"],inplace=True)

df.info()

